Balance: Balance Class Reference
Balance Class Reference
A controller class to read the sensors and control the motors.
#include <Balance.h>
Public Member Functions
Balance ()
Creates a controller which holds the functions that determine actuation signal.
void set_gains (void)
Set proportional and integral control gains.
void convert (accelBuf buffer)
Averages the previous 5 IMU values to avoid unwanted noise.
void set_setpoint (void)
Dynamically adjusts the setpoint value.
void control ()
Applies PI control to output a duty cycle for each motor.
Protected Attributes
float kp = 0
Proportional control gain.
float ki = 0
Integral control gain.
float kg = 0
Gyroscope sensitivity gain.
float set_x = 0
Setpoints for acceleration compare in terms of mG.
float set_y = 0
Setpoints for acceleration compare in terms of mG.
float esum_x = 0
Error sum for integral control in x direction.
float esum_y = 0
Error sum for integral control in y direction.
float x_accel
Averaged acceleration in the x direction.
float y_accel
Averaged acceleration in the y direction.
float z_accel
Averaged acceleration in the z direction.
Detailed Description
A controller class to read the sensors and control the motors.
The feedback from the IMU is converted to g's, compared to the appropriate reference value, and the error undergoes proportianal and integral algorithms to output an actuation signal for the motor driver.
Returns
A duty cycle expressed as an 8-bit integer for the range -100 to 100.
Definition at line 17 of file Balance.h.
Constructor & Destructor Documentation
Balance::Balance (void)
Creates a controller which holds the functions that determine actuation signal.
This is a simple constructor. It does not require any setup.
Definition at line 17 of file Balance.cpp.
Member Function Documentation
void Balance::control ()
Applies PI control to output a duty cycle for each motor.
Uses the error signal calculated from the setpoints for x and y to the current accelerations sensed in the x and y directions to calculate the appropriate actuation signal. The control gains convert the error in mG to voltage.
Definition at line 88 of file Balance.cpp.
References esum_x, esum_y, ki, kp, motor_A_actuation_signal, motor_B_actuation_signal, set_x, set_y, x_accel, and y_accel.
Referenced by task_controller::run().
void Balance::convert (accelBuf buffer)
Averages the previous 5 IMU values to avoid unwanted noise.
Takes the accelBuf structure, creates a total of all available X, Y and Z values and finds the average
Parameters
buffer A structure that holds the previous 5 acceleration data points for X, Y, and Z axis of the IMU
Definition at line 41 of file Balance.cpp.
References accelBuf::accel_buffer, accelData::data, x_accel, y_accel, and z_accel.
Referenced by task_controller::run().
void Balance::set_gains (void)
Set proportional and integral control gains.
Allows the user to input the necessary control gains.
Definition at line 26 of file Balance.cpp.
References ki, and kp.
Referenced by task_controller::run().
void Balance::set_setpoint (void)
Dynamically adjusts the setpoint value.
Uses acceleration information from both IMUs to output an appropriate reference value to compare against the feedback. This function was left simple for the controller used, but would ultimately be used to change the set points of the controller.
Definition at line 68 of file Balance.cpp.
References set_x, and set_y.
The documentation for this class was generated from the following files:
Balance.h
Balance.cpp