Balance: task_controller Class Reference
task_controller Class Reference
Task which uses accelerometer data to calculate motor actuation signals.
#include <task_controller.h>
Public Member Functions
task_controller (const char *p_name, unsigned portBASE_TYPE prio, size_t stacked, emstream *serpt, Balance *controller)
The constructor sets up the task object.
void run (void)
The run method call the functions of the controller in a loop.
Protected Attributes
Balance * controller
The controller that is used by the task to implement the control algorithm.
Detailed Description
Task which uses accelerometer data to calculate motor actuation signals.
This task uses the task share data made available from the IMU task to set the task shares for motor A and B actuation signals.
Definition at line 28 of file task_controller.h.
Constructor & Destructor Documentation
task_controller::task_controller (const char * p_name, unsigned portBASE_TYPE prio, size_t stacked, emstream * serpt, Balance * balance_controller)
The constructor sets up the task object.
Constructor for a controller object.
This constructor calls its parent class's constructor to actually do the work of creating the controller task.
Parameters
p_name A name for this task
prio The priority at which this task will run (should be low)
stacked The stack space to be used by the task (not much)
serpt A pointer to a serial device on which debugging messages are shown
balance_controller A pointer to a Balance controller used to call functions to determine the actuation signal
Definition at line 33 of file task_controller.cpp.
References controller.
Member Function Documentation
void task_controller::run (void)
The run method call the functions of the controller in a loop.
The run method that calculates the actuation signal of motors x and y.
This method
Definition at line 45 of file task_controller.cpp.
References accelerometer_A_data, Balance::control(), controller, Balance::convert(), and Balance::set_gains().
The documentation for this class was generated from the following files:
task_controller.h
task_controller.cpp